Create css.md
Byzanteam/handbook pull request #10
Opened 2019-02-28 04:01 UTC by moonRider

2019-02-28 15:20 UTC, fahchen commented
@vanppo @usernameisMan @Leecason 帮忙补充一下呢

2019-03-01 07:41 UTC, Leecason commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
这个需要么 写着好难受哦

2019-03-01 07:49 UTC, vanppo commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
这个还好吧 可以用工具来调整顺序的

2019-03-01 07:49 UTC, Leecason commented
数字小于0，不写出 0
```css
// good
a {
  opacity: .5;
}

// bad 
a {
  opacity: 0.5;
}
```

长度如果为 0 不写单位
```css
// good
a {
 width: 0;
}

// bad 
a {
  width: 0px;
}

// 如果为时间需要单位
transition-delay: 0s;
```

2019-03-01 07:55 UTC, Leecason commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
我觉得按类型来分好

2019-03-01 07:57 UTC, Leecason commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
https://sass-guidelin.es/zh/#section-23

2019-03-01 08:00 UTC, vanppo requested changes
还有就是 缩紧 空格 等等细节的地方。
然后 mixins 和 placeholder 最佳实践等等。

2019-03-01 08:00 UTC, vanppo commented on dev/front-end/css.md
> +1. `variables` -- 文件
partial 文件以 `_` 开头。
variables -> _variables

2019-03-01 08:00 UTC, vanppo commented on dev/front-end/css.md
> +1. `variables` -- 文件
normalize -> _normalize

2019-03-01 08:00 UTC, vanppo commented on dev/front-end/css.md
> +1. 对于复杂结构的 BEM(拥有多层嵌套)，比如 `B__E1--M1__E11__E111--M111` 取其中具有代表意义且不容易造成命名冲突的部分重新作为 Block 解决嵌套长度的问题
这里不是很好理解，能不能举个更形象的例子呢？带 DOM 结构的那种。

2019-03-01 08:29 UTC, fahchen commented
给一个 lint 文件出来吧

2019-03-05 11:30 UTC, moonRider commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
按类型来分不好控制，不适合团队规范(每个人的类型顺序并不一样)，但是字母顺序都是一样的

2019-03-05 11:47 UTC, moonRider commented on dev/front-end/css.md
> +1. 对于复杂结构的 BEM(拥有多层嵌套)，比如 `B__E1--M1__E11__E111--M111` 取其中具有代表意义且不容易造成命名冲突的部分重新作为 Block 解决嵌套长度的问题
list - B
list__item 
list__item__content

list__item 是 list 的 BE 结构, list__item__content 是 list 的 BEE 结构，如果 把 list__item 重定义为一个 item 的 B, 则 list__item__content 是 item 的 BE 结构，这个可以用来缩减命名长度

2019-03-05 12:51 UTC, vanppo commented on dev/front-end/css.md
> +1. 属性使用字母顺序排序
这个有没有用 https://github.com/sasstools/sass-lint/blob/master/docs/rules/property-sort-order.md

2019-03-08 02:40 UTC, moonRider commented on dev/front-end/css.md
> +1. `variables` -- 文件
这里的名字不等于具体实现，只是说明要有这些东西存在

2019-04-15 16:05 UTC, vanppo commented
> * [ ]  再给一个 lint 文件出来吧

@moonRider @fahchen @Leecason 
放到 Byzanteam 下面就没法删了，我先放到我自己仓库里面，没问题单独发布一下。https://github.com/vanppo/stylelint-config-byzanteam

2019-04-16 00:30 UTC, fahchen commented
没懂？

2019-04-16 02:03 UTC, vanppo commented
你要的 lint 文件呀

2019-04-16 05:50 UTC, fahchen commented
@moonRider 把 https://github.com/Byzanteam/stylelint-config 加上

2022-04-24 07:40 UTC, closed without merging