Update frontend.md
Byzanteam/handbook pull request #27
Opened 2020-11-19 02:31 UTC by moonRider

2020-11-19 02:37 UTC, fahchen commented on hiring/frontend.md
>  1. 有前端可视化开发经验，如 D3.js
可视化经验还要保留吗？

2022-04-18 04:12 UTC, fahchen requested changes
分成`初级`和`中高级`吧，我感觉`中级`和`高级`我们可以不用区分开去招聘

2022-04-18 04:12 UTC, fahchen commented on hiring/frontend.md
> +3. 熟悉前端各种框架 React/Vue/Angular 等，熟知框架的**设计原理（甚至源码）**，并有实际项目经验。
```suggestion
3. 熟悉前端各种框架 React/Vue/Angular 等，熟知框架的**设计原理（甚至源码）**，并有实际项目经验
```

2022-04-18 05:52 UTC, fahchen requested changes

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +8. 熟练使用 typescript 进行开发
```suggestion
8. 熟练使用 TypeScript 进行开发
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +2. 熟悉 nodejs，python，go 等后端语言，开发过简单的后台
这个不作要求

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +4. 熟悉函数式编程思想
这个不作要求

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +5. 良好的规范意识，熟悉 lint，ci 等
```suggestion
5. 良好的编程习惯及规范
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +7. 熟悉测试的一些基本理论
这个不作要求

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +6. 独立的思考能力，良好的创造力
这个不作要求，因为每个人的认知不一样都会觉得自己满足了，面试的时候考核就行了

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +1. 熟悉前端的工具，如 rollup，gulp等
```suggestion
1. 熟悉前端的工具，如 rollup，gulp 等
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +1. 计算机或相关专业本科及以上学历
```suggestion
1. 计算机或相关专业
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +4. 能熟练使用浏览器调试工具进行样式，脚本和网络的调试，定位bug，能找准测试的关键界点
```suggestion
4. 能熟练使用浏览器调试工具进行样式，脚本和网络的调试，定位 bug，能找准测试的关键界点
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +6. 熟悉 webpack，rollup 等打包工具，能进行一些简单的自定义配置
```suggestion
6. 会使用 webpack，rollup 等打包工具，能进行一些简单的自定义配置
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +7. 良好的表达能力，文档能力，善于学习，责任心强
文档能力移到加分项，其他的在面试中考核就好了
```suggestion
1. 良好的表达能力
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +1. 计算机或相关专业**重点本科**及以上学历，CET4+
```suggestion
1. 计算机或相关专业本科及以上学历
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +3. 熟悉前端各种框架 React/Vue/Angular 等，熟知框架的**设计原理（甚至源码）**，并有实际项目经验
`React/Vue/Angular` 和上面初级前端的描述里面的分隔符保持一致

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +3. 熟悉前端各种框架 React/Vue/Angular 等，熟知框架的**设计原理（甚至源码）**，并有实际项目经验
```suggestion
3. 熟悉前端各种框架 React/Vue/Angular 等，熟知框架的**实现原理**
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +4. 熟悉前端的自动化和规范工具 lint，ci，test 等
```suggestion
4. 了解前端的自动化和规范工具，如： GitHub Actions 等
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +5. 熟悉 Nodejs 语言，能使用 Nodejs 完成一些特定的任务
```suggestion
5. 了解 Nodejs 语言，能使用 Nodejs 完成工具链开发
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +7. 熟悉 webpack，rollup 等打包工具，并有一定的**调优和抉择**能力，能扩展其插件或 loader
`抉择`是啥意思？

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +1. 熟悉 AST，了解编译的相关知识
```suggestion
1. 了解编译的相关知识
```

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +2. 深厚的数学和算法能力
深厚这个词太过了

2022-04-18 05:52 UTC, fahchen commented on hiring/frontend.md
> +6. 熟练使用浏览器调试工具调试**内存，性能**等问题
这个放到加分项里面去

2022-04-18 06:13 UTC, vanppo commented on hiring/frontend.md
> +1. 熟悉前端的工具，如 rollup，gulp等
vite rollup webpack 吧 gulp 过时了

2022-04-19 00:40 UTC, fahchen commented on hiring/frontend.md
> +3. 熟悉前端各种框架（React，Vue，Angular）等，熟知框架的**实现原理**
```suggestion
3. 熟悉至少一种前端框架（React，Vue，Angular 等），熟知框架的**实现原理**
```

2022-04-19 00:40 UTC, fahchen commented on hiring/frontend.md
> +5. 熟悉 Nodejs 语言，能使用 Nodejs 完成工具链开发
```suggestion
5. 熟悉 Nodejs，能使用 Nodejs 完成工具链开发
```

2022-04-19 00:40 UTC, fahchen commented on hiring/frontend.md
> +6. 熟悉 webpack，rollup 等打包工具，并有一定的**调优**能力，能扩展其插件或 loader
把 vite 加上

2022-04-19 00:40 UTC, fahchen commented on hiring/frontend.md
> +8. 熟悉数据结构与算法相关知识，能完成常见数据结构的相关算法实现（例如 树的遍历）
```suggestion
8. 熟悉数据结构与算法相关知识
```

2022-04-24 07:39 UTC, fahchen approved these changes

2022-04-24 07:39 UTC, merged