docs/jason/beginner_guidance
Byzanteam/handbook pull request #37
Opened 2022-12-09 07:19 UTC by json2008

add beginner_guidance.md for green hands.

2022-12-09 07:43 UTC, fahchen requested changes

2022-12-09 07:43 UTC, fahchen commented on beginer_guidance.md
> +# 我所理解的pull-request流程
去掉这一行

2022-12-09 07:43 UTC, fahchen commented on beginer_guidance.md
> +## 一、开发前的准备工作。
注意格式
```suggestion
## 开发前的准备工作
```

2022-12-09 07:43 UTC, fahchen commented on beginer_guidance.md
> +1. 将公司的项目repo-X, fork到我自己的github帐户内(假定为：repo-Y)。
我们不允许 fork，我们是基于 branch 开发的

2022-12-09 07:43 UTC, fahchen commented on beginer_guidance.md
> +# 我所理解的pull-request流程
这个文件写到 `howto/github-flow.md` 里面o

2022-12-09 07:53 UTC, json2008 commented on beginer_guidance.md
> +# 我所理解的pull-request流程
ok
原本是个草案，直接copy过来了。

2022-12-09 07:55 UTC, json2008 commented on beginer_guidance.md
> +1. 将公司的项目repo-X, fork到我自己的github帐户内(假定为：repo-Y)。
基于branch开发？也就是每个人有开新分支的权限。但没有合并到main的权限？
需要多人review通过后？谁最后做合并？这些需要理清楚。

2022-12-09 08:00 UTC, json2008 commented on beginer_guidance.md
> +# 我所理解的pull-request流程
ok
后面我统一调整一次。

2022-12-09 08:08 UTC, fahchen commented on beginer_guidance.md
> +1. 将公司的项目repo-X, fork到我自己的github帐户内(假定为：repo-Y)。
每个项目不同，这些是每个 repo 单独设置的

2022-12-09 08:56 UTC, CptBreeza commented
这里要注意一下排版，参考[这篇](https://github.com/sparanoid/chinese-copywriting-guidelines)

2022-12-09 11:03 UTC, fahchen commented on beginer_guidance.md
> +1. 与repo-X的owner一道，沟通、建立（确立）ISSUE.（一个或多个）
产品开发每周迭代的时候会拆分和领取任务
对于 package 开发，使用 issues 或者 project（GitHub）进行管理

2022-12-09 11:03 UTC, fahchen commented on beginer_guidance.md
> +3. 在本地repo，git checkout -b feature/jason/genstage   # 在我本地repo上，开一个新分支上来开发（新增功能、修复bug、。。。）。分支的命名规范？
```
git fetch origin {default-branch}
git chcekout -b feat/fahchen/new-feature origin/{default-branch}
```

```
git fetch origin {default-branch}
git rebase origin/{default-branch}
```

2022-12-09 11:03 UTC, fahchen commented on beginer_guidance.md
> +4. 本地开发中，可能会有一个或多个本地的提交。# 对本地commit的规范要求？
参考 handbook

2022-12-09 11:03 UTC, fahchen commented on beginer_guidance.md
> +    2. 直至，此pr被owner接受。并被合并到repo-X的main中。
reviewer

2022-12-12 08:16 UTC, json2008 commented
这份文档，原本写在飞书。用于请教我所理解的 Pull-Request 流程是否正确？
放在此处有些不合适。

我把它 close 了。

2022-12-12 08:16 UTC, closed without merging